name: web-ext

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install web-ext
        run: npm install -g web-ext@7

      - name: Lint and Build
        run: |
          web-ext lint
          web-ext build -o --overwrite-dest --artifacts-dir web-ext-artifacts

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: web-ext-artifacts/

